-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.country
(
    code character(3) COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    population integer NOT NULL,
    gnp numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS public.world
(
    name character varying(50) COLLATE pg_catalog."default",
    continent character varying(50) COLLATE pg_catalog."default",
    population integer
);
END;